export const nodes = [ { s: 'A', x: 1, y: 1 },
                       { s: 'B', x: 2, y: 1 },
                       { s: 'B', x: 6, y: 1 },
                       { s: 'B', x: 7, y: 1 },
                       { s: 'B', x: 1, y: 2 },
                       { s: 'A', x: 2, y: 2 },
                       { s: 'B', x: 3, y: 2 },
                       { s: 'C', x: 4, y: 2 },
                       { s: 'B', x: 5, y: 2 },
                       { s: 'C', x: 6, y: 2 },
                       { s: 'B', x: 7, y: 2 },
                       { s: 'B', x: 1, y: 3 },
                       { s: 'A', x: 2, y: 3 },
                       { s: 'A', x: 3, y: 3 },
                       { s: 'C', x: 4, y: 3 },
                       { s: 'B', x: 5, y: 3 },
                       { s: 'C', x: 6, y: 3 },
                       { s: 'B', x: 7, y: 3 },
                       { s: 'B', x: 1, y: 4 },
                       { s: 'B', x: 2, y: 4 },
                       { s: 'C', x: 3, y: 4 },
                       { s: 'B', x: 4, y: 4 },
                       { s: 'B', x: 5, y: 4 },
                       { s: 'C', x: 6, y: 4 },
                       { s: 'B', x: 7, y: 4 },
                       { s: 'A', x: 1, y: 5 },
                       { s: 'B', x: 2, y: 5 },
                       { s: 'B', x: 3, y: 5 },
                       { s: 'A', x: 4, y: 5 },
                       { s: 'B', x: 5, y: 5 },
                       { s: 'B', x: 6, y: 5 },
                       { s: 'B', x: 7, y: 5 },
                     ];

export const grid = { w: 7, h: 5 };

export const message = "What has happened here?";
